
--welcome : Html Msg
--welcome =
--    node contentNode
--        [ class [ StepWelcome ] ]
--        [ headerBanner
--        , div []
--            [ h2 [] [ text "Hello!" ]
--            , p []
--                [ text "I'm looking for someone to share in an adventure..." ]
--            , p []
--                [ text "Do you believe in computer fairies? Their job is to protect all your private information. But, be ware, they don't exist!" ]
--            , p []
--                [ text "So who is protecting you? No one! In the land of bits and pixels there are no gods!" ]
--            , p []
--                [ text "What are you still doing in this screen? You better be going now, if you really wanna play..." ]
--            , div []
--                [ button [ onClick <| GoStep PickLocation ] [ text "I'M IN" ] ]
--            ]
--        ]